import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Navbar } from "@/components/Navbar/Navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} max-w-[1440px] w-full relative h-full mx-auto antialiased`}
      >
        <div className="absolute top-0 bottom-0 left-0 bg-[#0dbbac] rounded-full blur-[300px] w-[22rem] h-[32rem] -z-10"></div>
        <Navbar />
        {children}
        <div className="absolute right-0 top-0  bg-[#0dbbac] rounded-full blur-[300px] w-[22rem] h-[32rem] -z-10"></div>
      </body>
    </html>
  );
}
